import bpy
context = bpy.context
obj = context.object

namelist = [
["center_c_n","center"],
["ketu_c_n","pelvis"],
["asi1_r_n","leg.R"],
["asi2_r_n","shin.R"],
["asi3_r_n","foot.R"],
["asi4_r_n","toe.R"],
["asi1_l_n","leg.L"],
["asi2_l_n","shin.L"],
["asi3_l_n","foot.L"],
["asi4_l_n","toe.L"],
["kosi_c_n","spine1"],
["mune_c_n","spine2"],
["kubi_c_n","neck"],
["face_c_n","head"],
["_eye_r_n","eye.R"],
["_eye_l_n","eye.L"],
["kata_r_n","shoulder.R"],
["ude1_r_n","arm.R"],
["ude2_r_n","forearm.R"],
["ude3_r_n","hand.R"],
["kou_r_n","small_ring_adjust_r"],
["koyu1_r_n","pinky1.R"],
["koyu2_r_n","pinky2.R"],
["koyu3_r_n","pinky3.R"],
["kusu1_r_n","index1.R"],
["kusu2_r_n","index2.R"],
["kusu3_r_n","index3.R"],
["naka1_r_n","middle1.R"],
["naka2_r_n","middle2.R"],
["naka3_r_n","middle3.R"],
["hito1_r_n","pointer1.R"],
["hito2_r_n","pointer2.R"],
["hito3_r_n","pointer3.R"],
["oya1_r_n","thumb1.R"],
["oya2_r_n","thumb2.R"],
["oya3_r_n","thumb3.R"],
["kata_l_n","shoulder.L"],
["ude1_l_n","arm.L"],
["ude2_l_n","forearm.L"],
["ude3_l_n","hand.L"],
["kou_l_n","small_ring_adjust_l"],
["koyu1_l_n","pinky1.L"],
["koyu2_l_n","pinky2.L"],
["koyu3_l_n","pinky3.L"],
["kusu1_l_n","index1.L"],
["kusu2_l_n","index2.L"],
["kusu3_l_n","index3.L"],
["naka1_l_n","middle1.L"],
["naka2_l_n","middle2.L"],
["naka3_l_n","middle3.L"],
["hito1_l_n","pointer1.L"],
["hito2_l_n","pointer2.L"],
["hito3_l_n","pointer3.L"],
["oya1_l_n","thumb1.L"],
["oya2_l_n","thumb2.L"],
["oya3_l_n","thumb3.L"],
["suso1_r_n","suso1.R"],
["suso1_l_n","suso1.L"],
["suso2_r_n","suso2.R"],
["suso2_l_n","suso2.L"],
["pocket_r_n","pocket.R"],
["pocket_l_n","pocket.L"],
["ketu_r_sup","ketu_support.R"],
["ketu_l_sup","ketu_support.L"],
["asi2_r_sup","shin_support.R"],
["asi2_l_sup","shin_support.L"],
["asi1_twist_r_sup","hip_twist_support.R"],
["asi1_twist_l_sup","hip_twist_support.L"],
["",""],
]

for n in namelist:
    pb = obj.pose.bones.get(n[0])
    # continue if no bone of that name
    if pb is None:
        continue
    # rename
    pb.name = n[1]
